add curl command

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -220,19 +220,19 @@ workflows:
     steps:
       script@1:
         title: Send Test Results
-          inputs:
-            - content: |-
-                #!/usr/bin/env bash
-                # fail if any commands fails
-                set -e
+        inputs:
+          - content: |-
+              #!/usr/bin/env bash
+              # fail if any commands fails
+              set -e
 
-                # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
-                set -o pipefail
+              # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+              set -o pipefail
 
-                # debug log
-                set -x
-                
-                curl -X POST -H 'Content-type: application/json' --data '{"MESSAGE":"New Test Results!!!", "PLATFORM": ${PLATFORM}, "APP_VERSION": ${APP_VERSION}, "BUILD_NUMBER": ${BUILD_NUMBER}, "GIT_CLONE_COMMIT_HASH": ${GIT_CLONE_COMMIT_HASH}}' ${SLACK_TEST_RESULT_WEBHOOK_URL}
+              # debug log
+              set -x
+
+              curl -X POST -H 'Content-type: application/json' --data '{"MESSAGE":"New Test Results!!!", "PLATFORM": ${PLATFORM}, "APP_VERSION": ${APP_VERSION}, "BUILD_NUMBER": ${BUILD_NUMBER}, "GIT_CLONE_COMMIT_HASH": ${GIT_CLONE_COMMIT_HASH}}' ${SLACK_TEST_RESULT_WEBHOOK_URL}
       # - slack@3:
       #     inputs:
       #       - pretext: '*New $PLATFORM Test Results Available!*'
