add nvm step

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -132,10 +132,22 @@ workflows:
   _install-and-set-env:
     steps:
     - restore-npm-cache@1: {}
+    - nvm@1:
+        inputs:
+        - node_version: 18.14.1
     - script@1:
         title: Yarn Setup
         inputs:
-        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully\nset -o pipefail\n# debug log\nset -x\n\nif ! cat /etc/issue 2>/dev/null\nthen\nyarn setup:ci\nelse \n  stack=$( cat /etc/issue )\nfi\n\nif [[ $stack == *Ubuntu* ]]; then\n    # on ubuntu, yarn setup command will fail\n    # as patch-package doesn't have write access to the node_modules folder\n    # thus, we need to set write permission manually and rerun yarn\n    # Bitrise issue link https://support.bitrise.io/hc/en-us/requests/39436?page=1\n    sudo chown root .\n\n    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash\n\n    export NVM_DIR=\"$([ -z \"${XDG_CONFIG_HOME-}\" ] && printf %s \"${HOME}/.nvm\" || printf %s \"${XDG_CONFIG_HOME}/nvm\")\"\n    [ -s \"$NVM_DIR/nvm.sh\" ] && \\. \"$NVM_DIR/nvm.sh\"\n\n    echo \"Using node version 18.14.1\"\n    nvm install 18.14.1\n     \n    yarn setup:ci\nfi"
+        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# make
+            pipelines' return status equal the last command to exit with a non-zero
+            status, or zero if all commands exit successfully\nset -o pipefail\n#
+            debug log\nset -x\n\nif ! cat /etc/issue 2>/dev/null\nthen\nyarn setup:ci\nelse
+            \n  stack=$( cat /etc/issue )\nfi\n\nif [[ $stack == *Ubuntu* ]]; then\n
+            \   # on ubuntu, yarn setup command will fail\n    # as patch-package
+            doesn't have write access to the node_modules folder\n    # thus, we need
+            to set write permission manually and rerun yarn\n    # Bitrise issue link
+            https://support.bitrise.io/hc/en-us/requests/39436?page=1\n    sudo chown
+            root .\n\n    yarn setup:ci\nfi"
     - save-npm-cache@1: {}
     - script@1:
         title: Download Env Files
@@ -177,38 +189,23 @@ workflows:
     - script@1:
         title: Override Feature Flags Key
         inputs:
-        - content: |-
-            #!/usr/bin/env bash
-            # fail if any commands fails
-            set -e
-            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
-            set -o pipefail
-            # debug log
-            set -x
-
-            # Check if the environment variable USE_POSTHOG_TEST_FEATURE_FLAGS is set to "true"
-            if [ "$USE_TEST_FEATURE_FLAGS" = "true" ]; then
-
-                # Read the value of POSTHOG_FEATURE_FLAGS_KEY from .env.development file
-                feature_flags_key=$(grep '^POSTHOG_FEATURE_FLAGS_KEY=' .env.development | cut -d '=' -f2)
-
-                # Check if the value is not empty (found in .env.development)
-                if [ -n "$feature_flags_key" ]; then
-                    # Create a temporary file for the in-place edit
-                    temp_file=$(mktemp)
-
-                    # Replace the value of POSTHOG_FEATURE_FLAGS_KEY in the .env file and save it in the temporary file
-                    sed "s/^POSTHOG_FEATURE_FLAGS_KEY=.*/POSTHOG_FEATURE_FLAGS_KEY=$feature_flags_key/" .env > "$temp_file"
-
-                    # Replace the original .env file with the modified temporary file
-                    mv "$temp_file" .env
-
-                    echo "Updated POSTHOG_FEATURE_FLAGS_KEY in .env"
-                else
-                    echo "POSTHOG_FEATURE_FLAGS_KEY not found in .env.development or is empty."
-                fi
-                
-            fi
+        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# make
+            pipelines' return status equal the last command to exit with a non-zero
+            status, or zero if all commands exit successfully\nset -o pipefail\n#
+            debug log\nset -x\n\n# Check if the environment variable USE_POSTHOG_TEST_FEATURE_FLAGS
+            is set to \"true\"\nif [ \"$USE_TEST_FEATURE_FLAGS\" = \"true\" ]; then\n\n
+            \   # Read the value of POSTHOG_FEATURE_FLAGS_KEY from .env.development
+            file\n    feature_flags_key=$(grep '^POSTHOG_FEATURE_FLAGS_KEY=' .env.development
+            | cut -d '=' -f2)\n\n    # Check if the value is not empty (found in .env.development)\n
+            \   if [ -n \"$feature_flags_key\" ]; then\n        # Create a temporary
+            file for the in-place edit\n        temp_file=$(mktemp)\n\n        # Replace
+            the value of POSTHOG_FEATURE_FLAGS_KEY in the .env file and save it in
+            the temporary file\n        sed \"s/^POSTHOG_FEATURE_FLAGS_KEY=.*/POSTHOG_FEATURE_FLAGS_KEY=$feature_flags_key/\"
+            .env > \"$temp_file\"\n\n        # Replace the original .env file with
+            the modified temporary file\n        mv \"$temp_file\" .env\n\n        echo
+            \"Updated POSTHOG_FEATURE_FLAGS_KEY in .env\"\n    else\n        echo
+            \"POSTHOG_FEATURE_FLAGS_KEY not found in .env.development or is empty.\"\n
+            \   fi\n    \nfi"
   _send-notification-slack:
     steps:
     - slack@3:
@@ -252,8 +249,10 @@ workflows:
             Environment|${ENVIRONMENT}
             Branch|${BITRISE_GIT_BRANCH}
             Commit|${GIT_CLONE_COMMIT_HASH}
-        - title: ':kirby_dance: <https://media.tenor.com/jxPq6fvRcEwAAAAd/chris-farley-tommy.gif|Tests have passed on commit "$GIT_CLONE_COMMIT_MESSAGE_SUBJECT">'
-        - title_on_error: ':doom_mad: <https://media.tenor.com/NClbuZnSxSgAAAAC/what-shocked.gif|Tests failed on commit "$GIT_CLONE_COMMIT_MESSAGE_SUBJECT">'
+        - title: ':kirby_dance: <https://media.tenor.com/jxPq6fvRcEwAAAAd/chris-farley-tommy.gif|Tests
+            have passed on commit "$GIT_CLONE_COMMIT_MESSAGE_SUBJECT">'
+        - title_on_error: ':doom_mad: <https://media.tenor.com/NClbuZnSxSgAAAAC/what-shocked.gif|Tests
+            failed on commit "$GIT_CLONE_COMMIT_MESSAGE_SUBJECT">'
         - timestamp: "no"
         - color: '#40BA8E'
         - buttons: |
@@ -266,11 +265,26 @@ workflows:
     - script@1:
         title: Get App Version
         inputs:
-        - content: "#!/usr/bin/env bash\n\n# if branch is a release branch (\"release/2.0.1\" for example), grab version from branch name \n# else if tag is a release candidate tag (\"0.13.1-rc1\" for example), grab version from tag\nif [[ $BITRISE_GIT_BRANCH == *release/* ]]; then\n  arrIN=(${BITRISE_GIT_BRANCH//// })\n  version=${arrIN[1]}\nelif [[ $BITRISE_GIT_TAG =~ \"rc\" ]]; then\n  arrIN=(${BITRISE_GIT_TAG//-/ })\n  version=${arrIN[0]}\nelse\n  # else version will just be 0.0.0\n  version=\"0.0.0\"\nfi\n\nenvman add --key APP_VERSION --value \"${version}\""
+        - content: "#!/usr/bin/env bash\n\n# if branch is a release branch (\"release/2.0.1\"
+            for example), grab version from branch name \n# else if tag is a release
+            candidate tag (\"0.13.1-rc1\" for example), grab version from tag\nif
+            [[ $BITRISE_GIT_BRANCH == *release/* ]]; then\n  arrIN=(${BITRISE_GIT_BRANCH////
+            })\n  version=${arrIN[1]}\nelif [[ $BITRISE_GIT_TAG =~ \"rc\" ]]; then\n
+            \ arrIN=(${BITRISE_GIT_TAG//-/ })\n  version=${arrIN[0]}\nelse\n  # else
+            version will just be 0.0.0\n  version=\"0.0.0\"\nfi\n\nenvman add --key
+            APP_VERSION --value \"${version}\""
     - script@1:
         title: Get Build Number
         inputs:
-        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully\nset -o pipefail\n# debug log\nset -x\n\n# when a pipeline starts, it triggers both iOS and Android workflows\n# in order for iOS and Android to have different build numbers, we increment build number by 1 for Android\nif [ \"$PLATFORM\" = \"iOS\" ]; then\n  buildNumber=$BITRISE_BUILD_NUMBER       \nelse\n  buildNumber=$((BITRISE_BUILD_NUMBER+1))\nfi\n\nenvman add --key BUILD_NUMBER --value \"${buildNumber}\""
+        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# make
+            pipelines' return status equal the last command to exit with a non-zero
+            status, or zero if all commands exit successfully\nset -o pipefail\n#
+            debug log\nset -x\n\n# when a pipeline starts, it triggers both iOS and
+            Android workflows\n# in order for iOS and Android to have different build
+            numbers, we increment build number by 1 for Android\nif [ \"$PLATFORM\"
+            = \"iOS\" ]; then\n  buildNumber=$BITRISE_BUILD_NUMBER       \nelse\n
+            \ buildNumber=$((BITRISE_BUILD_NUMBER+1))\nfi\n\nenvman add --key BUILD_NUMBER
+            --value \"${buildNumber}\""
     - set-ios-info-plist-unified@1:
         title: Set iOS Version
         run_if: '{{enveq "PLATFORM" "iOS"}}'
@@ -417,25 +431,13 @@ workflows:
     - script@1:
         title: Detox
         inputs:
-        - content: |-
-            #!/usr/bin/env bash
-
-            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
-            set -o pipefail
-
-            # debug log
-            set -x
-
-            npm rebuild detox
-            QT_QPA_PLATFORM=xcb; ./node_modules/.bin/detox test --configuration android.internal.release.smoke.ci --headless --retries 1; test_result=$?
-            
-            RUN_ID=$(head -n 1 ./e2e/testrailRunId.txt) 
-            
-            envman add --key TESTRAIL_RUN --value $RUN_ID
-
-            if ((test_result != 0)); then
-              exit 1
-            fi
+        - content: "#!/usr/bin/env bash\n\n# make pipelines' return status equal the
+            last command to exit with a non-zero status, or zero if all commands exit
+            successfully\nset -o pipefail\n\n# debug log\nset -x\n\nnpm rebuild detox\nQT_QPA_PLATFORM=xcb;
+            ./node_modules/.bin/detox test --configuration android.internal.release.smoke.ci
+            --headless --retries 1; test_result=$?\n\nRUN_ID=$(head -n 1 ./e2e/testrailRunId.txt)
+            \n\nenvman add --key TESTRAIL_RUN --value $RUN_ID\n\nif ((test_result
+            != 0)); then\n  exit 1\nfi"
   ios:
     before_run:
     - _install-and-set-env
@@ -498,7 +500,7 @@ workflows:
         inputs:
         - content: |-
             #!/usr/bin/env bash
-            
+
             # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
             set -o pipefail
 
@@ -576,22 +578,9 @@ workflows:
     - script@1:
         title: Detox
         inputs:
-        - content: |-
-            #!/usr/bin/env bash
-
-            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
-            set -o pipefail
-
-            # debug log
-            set -x
-
-            npm rebuild detox
-            ./node_modules/.bin/detox test --configuration ios.internal.release.smoke.ci --retries 1; test_result=$?
-            
-            RUN_ID=$(head -n 1 ./e2e/testrailRunId.txt) 
-            
-            envman add --key TESTRAIL_RUN --value $RUN_ID
-
-            if ((test_result != 0)); then
-              exit 1
-            fi
+        - content: "#!/usr/bin/env bash\n\n# make pipelines' return status equal the
+            last command to exit with a non-zero status, or zero if all commands exit
+            successfully\nset -o pipefail\n\n# debug log\nset -x\n\nnpm rebuild detox\n./node_modules/.bin/detox
+            test --configuration ios.internal.release.smoke.ci --retries 1; test_result=$?\n\nRUN_ID=$(head
+            -n 1 ./e2e/testrailRunId.txt) \n\nenvman add --key TESTRAIL_RUN --value
+            $RUN_ID\n\nif ((test_result != 0)); then\n  exit 1\nfi"
