check testapk path

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -26,6 +26,7 @@ workflows:
         is_expand: false
     steps:
     - avd-manager@1:
+        run_if: '{{enveq "E2E" "true"}}'
         inputs:
         - api_level: "28"
         - emulator_id: emulator-5554
@@ -41,6 +42,7 @@ workflows:
         - module: $ANDROID_MODULE
         - arguments: :app:assembleInternalE2eAndroidTest
         - build_type: aab
+        - cache_level: all
         - variant: $ANDROID_BUILD_VARIANT
     - save-gradle-cache@1: {}
     - sign-apk@1:
@@ -58,31 +60,6 @@ workflows:
         - keystore_alias: $ANDROID_KEY_ALIAS
         - private_key_password: $ANDROID_KEY_PASSWORD
         - keystore_url: $BITRISEIO_ANDROID_KEY_STORE_URL
-  _build-android-e2e:
-    envs:
-    - PLATFORM: Android
-      opts:
-        is_expand: false
-    steps:
-    - install-missing-android-tools@3:
-        inputs:
-        - gradlew_path: $ANDROID_PROJECT_LOCATION/gradlew
-    - restore-gradle-cache@1: {}
-    - android-build-for-ui-testing@0:
-        inputs:
-        - project_location: $ANDROID_PROJECT_LOCATION
-        - variant: $ANDROID_BUILD_VARIANT
-        - module: $ANDROID_MODULE
-    - save-gradle-cache@1: {}
-    - sign-apk@1:
-        inputs:
-        - android_app: $BITRISE_AAB_PATH
-        - use_apk_signer: "true"
-        - debuggable_permitted: "false"
-        - keystore_url: $BITRISEIO_ANDROID_KEY_STORE_URL
-        - keystore_password: $ANDROID_STORE_PASSWORD
-        - keystore_alias: $ANDROID_KEY_ALIAS
-        - private_key_password: $ANDROID_KEY_PASSWORD
   _build-ios:
     envs:
     - PLATFORM: iOS
@@ -200,6 +177,7 @@ workflows:
         title: Set Android Version
         inputs:
         - new_version_name: $APP_VERSION
+        - version_code_offset: "1"
         - build_gradle_path: $BITRISE_SOURCE_DIR/$ANDROID_PROJECT_LOCATION/app/build.gradle
   android:
     before_run:
@@ -269,6 +247,25 @@ workflows:
       opts:
         is_expand: false
     steps:
+    - wait-for-android-emulator@1: {}
+    - script@1:
+        title: Start Detox
+        inputs:
+        - content: |
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+
+            # debug log
+            set -x
+
+            # npm rebuild detox
+            echo $BITRISE_APK_PATH_LIST
+
+            yarn ./node_modules/.bin/detox test --configuration android.internal.release.ci
     - script@1:
         inputs:
         - content: |
@@ -281,10 +278,6 @@ workflows:
             set -x
 
             sleep 5400
-    - wait-for-android-emulator@1: {}
-    - script@1:
-        inputs:
-        - content: "#!/usr/bin/env bash\n# fail if any commands fails\nset -e\n# make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully\nset -o pipefail\n# debug log\nset -x\n\nnpm rebuild detox\n\n./node_modules/.bin/detox test --configuration android.internal.release.ci \n"
   ios:
     before_run:
     - _install-and-set-env
