testing

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -290,6 +290,20 @@ workflows:
         - configuration: $IOS_CONFIGURATION
         - code_signing_allowed: "no"
         - log_formatter: xcpretty
+        - xcconfig_content: |-
+            SWIFT_ACTIVE_COMPILATION_CONDITIONS=$(inherited) DETOX
+    - script@1:
+        title: Testing
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
+            set -o pipefail
+
+            xcodebuild -showBuildSettings -workspace "$IOS_PROJECT_PATH" -scheme "$IOS_SCHEME" -configuration "$IOS_CONFIGURATION" | grep SWIFT_ACTIVE_COMPILATION_CONDITIONS
+            echo "YO"
     - script-runner@0:
         title: Create iOS Test Run
         inputs:
